version: "3.5"
services:
  db:
    image: mysql:5.7
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "db-data:/var/lib/mysql"
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  db-data:
